---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: parakeet
# description will be included in the image's metadata
description: silverblue + niri for aarch64 uefi

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: latest # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      keys:
        - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
      copr:
        - avengemedia/danklinux
    install:
      packages:
        - brave-origin
        - brightnessctl
        - btop
        - cargo
        - cava
        - chezmoi
        - cliphist
        - ddcutil
        - dialog
        - eog
        - fastfetch
        - fex-emu
        - fex-emu-rootfs-fedora
        - fex-emu-thunks
        - fira-code-fonts
        - freerdp
        - gnome-calculator
        - gnome-clocks
        - gparted
        - ImageMagick
        - jetbrainsmono-nerd-fonts
        - kitty
        - mangohud
        - mediawriter
        - mpv
        - niri
        - nmap-ncat
        - noctalia-shell
        - papers
        - python3-pip
        - qt6ct
        - screen
        - tailscale
        - telnet
        - vim
        - vulkan-tools
        - wayvnc
        - wlsunset
        - yazi
        - zed

    remove:
      packages:
        - htop
        - gnome-software
        - gnome-system-monitor

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.ranfdev.DistroShelf
          - io.github.flattool.Ignition
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - org.remmina.Remmina
          - page.codeberg.libre_menu_editor.LibreMenuEditor
          - io.github.kolunmi.Bazaar
          - io.missioncenter.MissionCenter
          - com.github.tchx84.Flatseal
          - org.atheme.audacious
          - page.tesk.Refine

  - type: signing

  - type: systemd
    system:
      enabled:
        - tailscaled
        - sshd

  - type: kargs
    kargs:
      - split_lock_detect=off
